
version: "3.0"
volumes:
  bundle:
  db:

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    tmpfs: /app/tmp
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/app